name: precise_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.3
  - pandas>=1.3
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  - xgboost=1.7.1
  - lightgbm>=3.3
  - pytorch>=1.10
  - shap>=0.44
  - scanpy=1.9.8
  - anndata=0.9.2
  - scipy
  - joblib
  - tqdm
  - boruta_py
  - pip
  - pip:
      - statsmodels
      - umap-learn
      - natsort
